[package]
name = "pw-screencast"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "pw-sc"
path = "src/main.rs"

[dependencies]
ashpd = "0.12"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
libc = "0.2"
